# REQUIRED
BOT_TOKEN = ""
OWNER_ID = 0
TELEGRAM_API = 0
TELEGRAM_HASH = ""

# OPTIONAL
MEGA_EMAIL = ""
MEGA_PASSWORD = ""
DOWNLOAD_DIR = "downloads"
STATUS_UPDATE_INTERVAL = 5
CONCURRENT_DOWNLOADS = 2
CONCURRENT_UPLOADS = 2
AUTHORIZED_CHATS = ""
SUDO_USERS = ""
MONGO_URI = ""
MONGO_DB_NAME = "sudo detail"
MONGO_COLLECTION_NAME = "mega bot detail"
VERIFY_EXPIRE = 0
TOKEN_TTL = 600
MIN_TOKEN_AGE = 10
VERIFY_PHOTO = ""
VERIFY_TUTORIAL = ""
SHORTLINK_SITE = ""
SHORTLINK_API = ""
SUPPORT_ID = ""
