# REQUIRED
BOT_TOKEN = ""
OWNER_ID = 0
TELEGRAM_API = 0
TELEGRAM_HASH = ""

# OPTIONAL
MEGA_EMAIL = ""
MEGA_PASSWORD = ""
DOWNLOAD_DIR = "downloads"
STATUS_UPDATE_INTERVAL = 5
CONCURRENT_DOWNLOADS = 2
CONCURRENT_UPLOADS = 2
AUTHORIZED_CHATS = ""
SUDO_USERS = ""
